  ### GET All users:
GET http://localhost:8081/api/v1/users
Authorization: bearer 
# add token

### Add a user:
POST http://localhost:8081/api/v1/users
Content-Type: application/json

{
 "firstName":"noa",
 "lastName":"nagar",
 "email":"noanagar1@gmail.com",
 "phone":"0555555555",
 "password":"Aa123!@#",
 "isBusiness":"true"
}


### Login:
POST http://localhost:8081/api/v1/users/login
Content-Type: application/json

{
  "email": "noanagar1234@gmail.com",
  "password": "Aa1234!@#"
}


### get user by id with JWT :
GET http://localhost:8081/api/v1/users/userId
Authorization: bearer 
# add token

### GET user by admin
GET http://localhost:8081/api/v1/users/userId
Authorization: bearer 
# add token

### PUT update uaer:
PUT http://localhost:8081/api/v1/users/userId
Authorization: bearer
Content-Type: application/json

{
 "firstName":"noa",
 "lastName":"nagar",
 "email":"noanagar1234@gmail.com",
 "phone":"0555555555",
 "password":"Aa123!@#",
 "isBusiness":"true"
}

### change status of user
PATCH http://localhost:8081/api/v1/users/userId
Authorization: bearer 
# add token
Content-Type: application/json

### DELETE user
DELETE http://localhost:8081/api/v1/users/userId
Authorization: bearer 
# add token


