### get all cards
GET http://localhost:8080/api/v1/cards

### create new card
POST http://localhost:8080/api/v1/cards/userId
Content-Type: application/json

{
"url":"........",
"alt":"alt",
"description":"description",
"firstName":"noa",
"lastName":"nagar",
"email":"noanagar1@gmail.com",
"phone":"0555555555",
"location": "south",
"jobType": "developer",
"domain": "full stack",
"studies": "studies",
"years": 2,
"userId":"65db115a1814e4bb4799a0a2"
}

### get my card
GET http://localhost:8080/api/v1/cards/myCard/userId
Authorization: bearer 
# add token
Content-Type: application/json

### get card by id
GET http://localhost:8080/api/v1/cards/cardId

### edit card
PUT http://localhost:8080/api/v1/cards/cardId
Authorization: bearer 
# add token
Content-Type: application/json

{
"url":"........E",
"alt":"alt",
"description":"description",
"firstName":"noa",
"lastName":"nagar",
"email":"noanagar1@gmail.com",
"phone":"0555555555",
"location": "south",
"jobType": "developer",
"domain": "full stack",
"studies": "studies",
"years": 2,
"userId":"65db115a1814e4bb4799a0a2"
}


### delete card
DELETE http://localhost:8080/api/v1/cards/cardId
Authorization: bearer 
# add token
Content-Type: application/json


